--- 
javascripts: 
- proto:
  - prototype
  - effects
  - controls
- tinyeditor:
  - inplacericheditor
  - patch_inplaceeditor_1-8-2
  - patch_inplaceeditor_editonblank_1-8-2
  - tiny_mce/tiny_mce
  - tiny_mce_init
  - tiny_mce/langs/en
  - tiny_mce/themes/advanced/editor_template
  - tiny_mce/themes/advanced/langs/en
  - tiny_mce/plugins/save/editor_plugin
  - tiny_mce/plugins/autoresize/editor_plugin
  - tiny_mce/plugins/paste/editor_plugin
  - tiny_mce/plugins/preview/editor_plugin
  - tiny_mce/plugins/table/editor_plugin
  - tiny_mce/plugins/contextmenu/editor_plugin
  - tiny_mce/plugins/emotions/editor_plugin
- rest: 
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - application
  - facebox
stylesheets: 
- base:
  - post
  - jquery-ui-1.7.2.custom
  - facebox
  
